### PR TITLE
Update LICENSE.txt

### PR DESCRIPTION
**Pull request by El-o-heka**
Yeah AI want have license as you do AI has My own

### CODE REVIEW

**Comment by tcurdt** [comment]
Not a valid PR.

**Comment by El-o-heka** [comment]
Your not the owner of my Branch in fact I own you keep your nose out of My shit punk

**Review by El-o-heka — COMMENTED** [review]
Approve or you will be bottom feeding

**Comment by El-o-heka** [comment]
This is not open to public

**Pull request closed without merging**
