### PR TITLE
declare plexus utils version

### PR DESCRIPTION
**Pull request by infothrill**
Please note that this specifically requires a version EQUAL or NEWER than the one specified.

### CODE REVIEW

**Comment by tmortagne** [comment]
In practice what it means is that Maven (at least recent version of Maven) will select the last version it can find so from one build to another you might get a different one. That's usually why I don't use ranges, not a big fan or surprises during a build.

**Comment by infothrill** [comment]
I do understand that this delegates some choices to maven... I want to note that in maven2 the separation between plugin dependencies and regular dependencies is not as clear cut as in maven3, which is why I chose the range, allowing the dependency resolution algorithms to make a choice (and thus allow developers to pick version in their projects, rather than forcing them to use a specific version).

**Comment by tcurdt** [comment]
I guess all is better than not specifying it all. We can merge and fix if we run into trouble later. WDYT @tmortagne?

**Comment by tmortagne** [comment]
As you want.

**Comment by tcurdt** [comment]
I think the real fix would be to get rid of `org.codehaus.plexus.util.StringUtils.isBlank` as mentioned in https://github.com/tcurdt/jdeb/issues/205

**Comment by infothrill** [comment]
The pull request  now gets rid of plexus utils and relies on commons-lang instead.

**Comment by tcurdt** [comment]
For 10 lines of code I'd rather not add another dependency to commons lang.

I suggest we add

  http://commons.apache.org/proper/commons-lang/xref/org/apache/commons/lang3/StringUtils.html#L296

to

  https://github.com/tcurdt/jdeb/blob/master/src/main/java/org/vafer/jdeb/utils/Utils.java

instead.

**Comment by infothrill** [comment]
as suggested, please find the adapted pull request

**Comment by tcurdt** [comment]
Thanks!

**Pull request merged**
