### PR TITLE
Marked Mojo as thread-safe. This closes #256.

### LINKED ISSUE #256: Maven warns that jdeb is not marked as thread-safe
If I use the jdeb plugin and execute with multiple threads, e.g. `mvn package -T8`, Maven reports the following warning:

```
[WARNING] *****************************************************************
[WARNING] * Your build is requesting parallel execution, but project      *
[WARNING] * contains the following plugin(s) that are not marked as       *
[WARNING] * @threadSafe to support parallel building.                     *
[WARNING] * While this /may/ work fine, please look for plugin updates    *
[WARNING] * and/or request plugins be made thread-safe.                   *
[WARNING] * If reporting an issue, report it against the plugin in        *
[WARNING] * question, not against maven-core                              *
[WARNING] *****************************************************************
[WARNING] The following plugins are not marked @threadSafe:
[WARNING] org.vafer:jdeb:1.5
[WARNING] *****************************************************************
```

Is jdeb thread safe?

### PR DESCRIPTION
**Pull request by dheid**
I tested this with multiple Maven projects using eight threads. It works like a charm! :smile:

### CODE REVIEW

**Comment by tmortagne** [comment]
Would be nicer to have a pull request with only what it's supposed to do. I can see a few broken formatting in that diff.

**Comment by dheid** [comment]
Okay, I will keep that in mind. Sorry for that!Am 06.04.2017 16:00 schrieb Thomas Mortagne <notifications@github.com>:Would be nicer to have a pull request with only what it's supposed to do. I can see a few broken formatting in that diff.

**Comment by dheid** [comment]
I cannot reproduce the unit test fail on AppVeyor, because I don't have a Windows machine. But I think, this has nothing to do with my changes.

**Comment by tmortagne** [comment]
> I cannot reproduce the unit test fail on AppVeyor, because I don't have a Windows machine. But I think, this has nothing to do with my changes.

Yes this test is currently failing on master too as far as I can see.

**Comment by tcurdt** [comment]
Yeah, don't worry about the appveyor - we just don't have anyone with access to a windows dev machine to look into it. I am not sure I want to go to the lengths of installing one in a vm just for that.

**Comment by dheid** [comment]
Okay, that's relieving. :) Shall I create a new pull request without the formatting stuff?

**Comment by tmortagne** [comment]
No need to create a new pull request, you can simply push a new commit in your branch which revert the formatting changes (github allows squashing a pull request).

**Comment by dheid** [comment]
Okay, it should be clean now.

**Comment by dheid** [comment]
Argh... I tried to squash the commits, but that resulted in even more commits... Sorry for that!

**Comment by tmortagne** [comment]
> Argh... I tried to squash the commits, but that resulted in even more commits... Sorry for that!

No need, we can ask github to squash when applying the pull request.

**Comment by tmortagne** [comment]
Applied, thanks !

**Pull request merged**
