### PR TITLE
Issue #628 : Updated the compiler source and target to 11 and added X…

### PR DESCRIPTION
**Pull request by harshal301002**
…lint unchecked

### CODE REVIEW

**Comment by tcurdt** [comment]
[Java 8 is still LTS](https://en.wikipedia.org/wiki/Java_version_history). Despite being acient I am not sure if we can/should upgrade to 11 yet.

But configuring the plugin sure should be done.

**Comment by harshal301002** [comment]
@tcurdt Yes you are right, there is no guarantee that the upgrade will not break the code. I'll try to re-configure.

**Comment by tcurdt** [comment]
Are you planing on updating the PR?

**Comment by harshal301002** [comment]
@tcurdt Yes, working on it.

**Pull request closed without merging**
